export const FETCH_USER_PENDING = 'FETCH_USER_PENDING';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
export const FETCH_USER_FAIL = 'FETCH_USER_FAIL';

export const UPDATE_USER_PENDING = 'UPDATE_USER_PENDING';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_FAIL = 'UPDATE_USER_FAIL';
export const CHANGE_PAGE = 'CHANGE_PAGE';
export const UPDATE_USER_FIELD = 'UPDATE_USER_FIELD';

export const NAVIGATE_HOME = 'NAVIGATE_HOME';

export const USERS_LIST_PENDING = 'USERS_LIST_PENDING';
export const USERS_LIST_SUCCESS = 'USERS_LIST_SUCCESS';
export const USERS_LIST_FAIL = 'USERS_LIST_FAIL';

export const CLEAR_DATA = 'CLEAR_DATA';
export const CLEAR_USER_REDUCER = 'CLEAR_USER_REDUCER';
